### ISSUE TITLE
build.sh is careless with encrypted variables

### ISSUE THREAD

**Issue by ndw** [travis-ci/travis-encrypt#1]
This feels like it should be a bug on travis-build, but that repo doesn't seem to accept issues.

If you encrypt an environment variable that contains a ")", travis falls over:

```
$ export DELTA_PASS=[secure]
/home/travis/build.sh: eval: line 41: syntax error near unexpected token `)'
/home/travis/build.sh: eval: line 41: `export DELTA_PASS=7^xxx1s)'
```

**Comment by BanzaiMan** [comment]
Please use the issue tracker in the main repository in the future: https://github.com/travis-ci/travis-ci/issues

This is a known issue and documented in http://docs.travis-ci.com/user/encryption-keys/#Note-on-escaping-certain-symbols
